version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    default_reviewers:
      - jreese802
    update_schedule: live
    allowed_updates:
      - match:
          update_type: security